uniticket/accounts/urls.py
from django.urls import path

from . settings import EDITABLE_FIELDS
from . views import changeData, confirmEmail


app_name = "accounts"

if EDITABLE_FIELDS:
    urlpatterns = [
        # url(r'^login/$', Login, name='login'),
        # path('logout', Logout, name='logout'),
        path('account/edit/', changeData, name='change_data'),
        path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),
    ]
else: # pragma: no cover
    urlpatterns = []

uniticket/api_rest/urls.py
from django.urls import path, re_path
from django.utils.text import slugify

from rest_framework import routers
from rest_framework.renderers import JSONOpenAPIRenderer
from rest_framework.schemas import get_schema_view

from api_rest.views import generic, manager, operator, user

from uni_ticket.settings import MANAGEMENT_URL_PREFIX


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', generic.UserViewSet)
router.register('groups', generic.GroupViewSet)

app_name = "api_rest"

urlpatterns = [
    # path('api/', include(router.urls)),
    # path('api-auth/', include(rest_framework.urls, 'rest_framework',)),

    re_path('^openapi/$',  get_schema_view(**{}), name='openapi-schema'),
    re_path('^openapi.json/$', get_schema_view(renderer_classes = [JSONOpenAPIRenderer], **{}), name='openapi-schema-json'),

    # generic
    path('api/strutture/list/', generic.TicketAPIStruttureList.as_view(), name='api-strutture-list'),
    path('api/ticket/category/list/', generic.TicketAPITicketCategoryList.as_view(),name='api-ticket-category-list'),

    # user
    path('api/<slug:structure_slug>/<slug:category_slug>/ticket/new/', user.TicketAPIView.as_view(), name='api-new-ticket'),
    path('api/ticket/<str:ticket_uid>/', user.TicketAPIDetail.as_view(), name='api-view-ticket'),
    path('api/ticket/user/list/', user.TicketAPIListCreated.as_view(), name='api-ticket-user-list'),
    path('api/ticket/close/<str:ticket_id>/', user.TicketAPIClose.as_view(), name='api-ticket-close'),

    # manager
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/unassigned/count/', manager.TicketAPIUnassignedCounter.as_view(), name='api-manager-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/open/count/', manager.TicketAPIOpenCounter.as_view(), name='api-manager-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/my-open/count/', manager.TicketAPIMyOpenCounter.as_view(), name='api-manager-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/messages/count/', manager.TicketAPIMessagesCounter.as_view(), name='api-manager-tickets-messages-count'),

    # operator
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/unassigned/count/', operator.TicketAPIUnassignedCounter.as_view(), name='api-operator-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/open/count/', operator.TicketAPIOpenCounter.as_view(), name='api-operator-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/my-open/count/', operator.TicketAPIMyOpenCounter.as_view(), name='api-operator-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/messages/count/', operator.TicketAPIMessagesCounter.as_view(), name='api-operator-tickets-messages-count'),
]

uniticket/app_io/urls.py
from django.urls import path

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from . views import *


app_name = "app_io"


base = f"{MANAGEMENT_URL_PREFIX['manager']}/<str:structure_slug>/categories/<str:category_slug>/app-io/services"


urlpatterns = [
    path(f'{base}/new/', new, name='app_io_services_new'),
    path(f'{base}/<int:service_id>/edit/', edit, name='app_io_services_edit'),
    path(f'{base}/<int:service_id>/enable/', enable, name='app_io_services_enable'),
    path(f'{base}/<int:service_id>/disable/', disable, name='app_io_services_disable'),
    path(f'{base}/<int:service_id>/delete/', delete, name='app_io_services_delete'),
]

uniticket/chat/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . api import ChatMessageModelViewSet, UserModelViewSet
from . import views

router = DefaultRouter()
router.register(r'message', ChatMessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')

app_name = "chat"

urlpatterns = [
    path(r'api/chat/', include(router.urls)),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('chat/random-vc-provider', views.random_vc_provider, name='random_vc_provider'),
]

uniticket/uni_ticket/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import path, re_path
from django.utils.text import slugify
from django.views.generic import RedirectView

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from .decorators import is_manager, is_operator, is_super_admin, is_the_owner
from .views import datatables, generic, management, manager, operator, user


app_name = "uni_ticket"

_dashboard_name = "dashboard"

# System/Generic URLs
# ticket = 'ticket/<str:ticket_id>'
ticket = "tickets/<str:ticket_id>"
urlpatterns = [
    path("", RedirectView.as_view(url="/{}/".format(_dashboard_name))),
    # Router url di responsabilità su struttura (manager/operator/user)
    re_path(
        r"^manage/(?:(?P<structure_slug>[-\w]+)(/)?)?$", generic.manage, name="manage"),
    # Attachments download
    path(
        "{}/download/attachment/<str:attachment>/".format(ticket),
        generic.download_attachment,
        name="download_attachment",
    ),
    path(
        "{}/messages/<str:reply_id>/download/attachment/".format(ticket),
        generic.download_message_attachment,
        name="download_message_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/attachment/".format(ticket),
        generic.download_task_attachment,
        name="download_task_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/closing-attachment/".format(ticket),
        generic.download_task_closing_attachment,
        name="download_task_closing_attachment",
    ),
    path(
        "<str:structure_slug>/<str:category_slug>/conditions/<int:condition_id>/download/attachment",
        generic.download_condition_attachment,
        name="download_condition_attachment",
    ),
    # Delete ticket message
    path(
        "messages/delete/<str:ticket_message_id>/",
        generic.ticket_message_delete,
        name="message_delete",
    ),
    path(
        "email-notify/update/", generic.email_notify_change, name="email_notify_change"
    ),
    path(
        "print/ticket/<str:ticket_id>/",
        user.ticket_detail_print,
        name="ticket_detail_print",
    ),
    path(
        "print/ticket/<str:ticket_id>/pdf/",
        user.download_ticket_pdf,
        name="ticket_detail_print_pdf",
    ),
]

# Datatables URLs
structure = "<str:structure_slug>"
urlpatterns += [
    # User json
    path(
        "user_all_tickets.json",
        datatables.user_all_tickets,
        name="user_all_tickets_json",
    ),
    path(
        "user_opened_ticket.json",
        datatables.user_opened_ticket,
        name="user_opened_ticket_json",
    ),
    path(
        "user_closed_ticket.json",
        datatables.user_closed_ticket,
        name="user_closed_ticket_json",
    ),
    path(
        "user_unassigned_ticket.json",
        datatables.user_unassigned_ticket,
        name="user_unassigned_ticket_json",
    ),
    # Manager json
    path(
        "{}/manager_unassigned_ticket.json".format(structure),
        datatables.manager_unassigned_ticket,
        name="manager_unassigned_ticket_json",
    ),
    path(
        "{}/manager_opened_ticket.json".format(structure),
        datatables.manager_opened_ticket,
        name="manager_opened_ticket_json",
    ),
    path(
        "{}/my/manager_opened_ticket.json".format(structure),
        datatables.manager_my_opened_ticket,
        name="manager_my_opened_ticket_json",
    ),
    path(
        "{}/manager_closed_ticket.json".format(structure),
        datatables.manager_closed_ticket,
        name="manager_closed_ticket_json",
    ),
    path(
        "{}/manager_all_tickets.json".format(structure),
        datatables.manager_all_tickets,
        name="manager_all_tickets_json",
    ),
    # Operator json
    path(
        "{}/operator_unassigned_ticket.json".format(structure),
        datatables.operator_unassigned_ticket,
        name="operator_unassigned_ticket_json",
    ),
    path(
        "{}/operator_opened_ticket.json".format(structure),
        datatables.operator_opened_ticket,
        name="operator_opened_ticket_json",
    ),
    path(
        f"{structure}/my/operator_opened_ticket.json",
        datatables.operator_my_opened_ticket,
        name="operator_my_opened_ticket_json",
    ),
    path(
        f"{structure}/operator_closed_ticket.json",
        datatables.operator_closed_ticket,
        name="operator_closed_ticket_json",
    ),
    path(
        f"{structure}/operator_all_tickets.json",
        datatables.operator_all_tickets,
        name="operator_all_tickets_json",
    ),
]

# Management URLs (manager and operator)
base = "manage/<str:structure_slug>"
tickets = "{}/tickets".format(base)
# ticket = '{}'.format(tickets)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)

urlpatterns += [
    # Export CSV
    # path('{}/export-csv/'.format(tickets), management.export_category_csv, name='export_category_csv'),
    # Export csv/zip
    path(
        "{}/export_detailed_report/".format(tickets),
        management.export_detailed_report,
        name="manage_export_detailed_report",
    ),
    # Tickets
    path(
        "{}/opened/".format(tickets),
        management.manage_opened_ticket_url,
        name="manage_opened_ticket_url",
    ),
    path(
        "{}/unassigned/".format(tickets),
        management.manage_unassigned_ticket_url,
        name="manage_unassigned_ticket_url",
    ),
    path(
        "{}/closed/".format(tickets),
        management.manage_closed_ticket_url,
        name="manage_closed_ticket_url",
    ),
    path(
        "{}/".format(tickets),
        management.manage_not_closed_ticket_url,
        name="manage_not_closed_ticket_url",
    ),
    path("{}/".format(tickets), management.manage_ticket_url,
         name="manage_ticket_url"),
    path(
        "{}/".format(ticket_id),
        management.manage_ticket_url_detail,
        name="manage_ticket_url_detail",
    ),
    path(
        "{}/messages/".format(ticket_id),
        management.ticket_message_url,
        name="manage_ticket_message_url",
    ),
    path(
        "{}/notes/".format(ticket_id),
        management.ticket_notes_url,
        name="manage_ticket_notes_url",
    ),
    path(
        "{}/notes/<int:note_id>/".format(ticket_id),
        management.ticket_note_url,
        name="manage_ticket_note_url",
    ),
    path(
        "{}/notes/<str:note_id>/delete/".format(ticket_id),
        management.ticket_note_delete,
        name="manage_ticket_note_delete",
    ),
    path(
        "{}/competence/add/".format(ticket_id),
        management.ticket_competence_add_url,
        name="add_ticket_competence_url",
    ),
    path(
        "{}/competence/leave/".format(ticket_id),
        management.ticket_competence_leave,
        name="leave_ticket_competence",
    ),
    path(
        "{}/dependence/add/".format(ticket_id),
        management.ticket_dependence_add_url,
        name="add_ticket_dependence_url",
    ),
    path(
        "{}/dependence/remove/<str:main_ticket_id>/".format(ticket_id),
        management.ticket_dependence_remove,
        name="remove_ticket_dependence",
    ),
    path(
        "{}/close/".format(ticket_id), management.ticket_close_url, name="close_ticket"
    ),
    path(
        "{}/reopen/".format(ticket_id), management.ticket_reopen, name="reopen_ticket"
    ),
    path(
        "{}/assign-offices/".format(ticket_id),
        management.ticket_taken_by_unassigned_offices,
        name="ticket_taken_by_unassigned_offices",
    ),
    # path('{}/assign/<str:destination_structure_slug>/<str:office_slug>/'.format(ticket_id), management.ticket_taken_by_unassigned_office, name='ticket_taken_by_unassigned_office'),
    # Task
    path(
        "{}/add/".format(task), management.task_add_new_url, name="add_ticket_task_url"
    ),
    path(
        "{}/".format(task_id), management.task_detail_url, name="manage_task_detail_url"
    ),
    path("{}/close/".format(task_id),
         management.task_close_url, name="close_task"),
    path("{}/delete/".format(task_id),
         management.task_remove, name="task_remove"),
    path("{}/riapri/".format(task_id),
         management.task_reopen, name="reopen_task"),
    path(
        "{}/edit/remove-attachment/".format(task_id),
        management.task_attachment_delete,
        name="manage_elimina_allegato_task",
    ),
    path("{}/edit/".format(task_id), management.task_edit_url, name="edit_task"),
]

# Manager URLs
base = "{}/<str:structure_slug>".format(
    slugify(MANAGEMENT_URL_PREFIX["manager"]))
tickets = "{}/tickets".format(base)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)
offices = "{}/offices".format(base)
office = "{}/office".format(offices)
office_id = "{}/<str:office_slug>".format(office)
categories = "{}/categories".format(base)
# category = '{}/category'.format(categories)
category_id = "{}/<str:category_slug>".format(categories)
cat_input = "{}/input".format(category_id)
cat_input_id = "{}/<int:module_id>".format(cat_input)
condition = "{}/conditions".format(category_id)
condition_id = "{}/<int:condition_id>".format(condition)
default_reply = "{}/default_replies".format(category_id)
default_reply_id = "{}/<int:default_reply_id>".format(default_reply)
category_task = "{}/default-tasks".format(category_id)
category_task_id = "{}/<str:task_id>".format(category_task)

structure_protocol_configurations = "{}/settings/protocol-configurations".format(
    base)
structure_protocol_configuration = "{}/<int:configuration_id>".format(
    structure_protocol_configurations
)

category_protocol_configurations = "{}/protocol-configurations".format(
    category_id)
category_protocol_configuration = "{}/<int:configuration_id>".format(
    category_protocol_configurations
)

urlpatterns += [
    path(

uniticket/uni_ticket_bootstrap_italia_template/templates/user/new_chat_preload.html
{% extends "base_page_schema.html" %}

{% load chat_tags %}
{% load i18n %}
{% load static %}
{% load uni_ticket_tags %}

{% block menu_links %}
{% include 'user/main_menu.html' %}
{% endblock menu_links %}

{% block top_buttons %}
<a role="button" class="btn btn-outline-secondary"
   href="{% url 'uni_ticket:user_dashboard' %}">
    <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
    </svg> {% trans "Torna alla Dashboard" %}
</a>
{% endblock top_buttons %}

{% block page_content %}
<b><label for="structure_slug">{% trans "Struttura" %}</label></b>
<div class="bootstrap-select-wrapper">
    <select id="structure_slug" name="structure_slug" title="{% trans 'A chi è indirizzata la richiesta?' %}">
        <option value="" selected>{% trans "Scegli un'opzione" %}</option>
        {% for struttura in strutture %}
        <option value="{{ struttura.slug }}"{% if struttura.slug == structure_slug %} selected{% endif %}>{{ struttura }}</option>
        {% endfor %}
    </select>
</div>

<div class="mt-4">
    {% if not structure_slug %}
        <div class="alert alert-warning" role="alert">
          {% trans "Seleziona la struttura con la quale collegarti in Chat" %}
        </div>
    {% else %}
        {% structure_operator_online request.user structure_slug as operator_online %}
        {% app_is_installed "chat" as chat_installed %}
        {% app_is_installed "channels" as channels_installed %}
        {% if chat_installed and channels_installed and operator_online %}
            <a role="button" class="btn btn-success" href="{% url 'chat:room' room_name=structure_slug %}">
                <svg class="icon icon-xs icon-white">
                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-user"></use>
                </svg> {% trans "Entra in Chat" %}
            </a>
        {% else %}
            <div class="alert alert-danger" role="alert">
              {% trans "Nessun operatore al momento disponibile in Chat" %}
            </div>
        {% endif %}
    {% endif %}
</div>

{% endblock page_content %}

{% block extra_scripts %}
<script src="{% static 'js/accessible-autocomplete.2.0.4.min.js' %}"></script>
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function () {
    let structureElement = document.querySelector('#structure_slug');
    let structureAutocomplete = new accessibleAutocomplete.enhanceSelectElement({
        selectElement: structureElement,
        showAllValues: true,
        defaultValue: '',
        placeholder: "- {% trans 'Scegli una opzione' %}- ",
        autoselect: false,
        showNoOptionsFound: false,
        dropdownArrow: () => '',
        onConfirm:  (selected) => {
            const selectedStructure = Array.from(structureElement.options).find(option => option.textContent === selected);
            if (selectedStructure) {
                {% if structure_slug %}
                window.location.href = replace_last_param(window.location.href, selectedStructure.value);
                {% else %}
                window.location.href = window.location.href + selectedStructure.value;
                {% endif %}
            }
        }
    });
});

function replace_last_param(url, new_param){
    return url.split('/').slice(0,-2).join('/')+'/'+new_param
}
</script>
{% endblock extra_scripts %}

uniticket/uni_ticket_bootstrap_italia_template/templates/user/ticket_detail.html
{% extends "base_page_schema.html" %}

{% load i18n %}
{% load static %}
{% load uni_ticket_tags %}

{% block menu_links %}
{% include 'user/main_menu.html' %}
{% endblock menu_links %}

{% block right_button %}
{% ticket_has_been_taken ticket=ticket as ticket_taken %}
<div class="pull-end">
    <a role="button" class="btn btn-outline-secondary"
       href="{% url 'uni_ticket:ticket_detail_print' ticket_id=ticket.code %}"
       target="_blank" rel="noopener noreferrer"
       data-bs-toggle="tooltip"
       title="{% trans 'Versione stampabile' %}">
        <svg class="icon icon-xs">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-print"></use>
        </svg>
    </a>
    <a role="button" class="btn btn-outline-secondary"
       href="{% url 'uni_ticket:ticket_detail_print_pdf' ticket_id=ticket.code %}"
       target="_blank" rel="noopener noreferrer"
       data-bs-toggle="tooltip"
       title="{% trans 'Versione PDF' %}">
        <svg class="icon icon-xs">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-file-pdf-ext"></use>
        </svg>
    </a>
</div>
{% endblock %}

{% block under_content_title %}
    {% ticket_has_been_taken ticket=ticket as ticket_taken %}
    {% if not ticket.is_closed and not ticket_taken and ticket_assignments.count == 1 %}
        {% include "ticket_protocol_required_alert.html" with ticket=ticket %}
        {% if not ticket.protocol_number %}
        <div class="alert alert-info alert-dismissible fade show mb-5" role="alert">
          {% trans "E' possibile <b>modificare</b> o <b>eliminare</b> la richiesta fino a quando questa non sia stata assegnata ad un operatore" %}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
          </button>
        </div>
        {% endif %}
    {% endif %}
{% endblock under_content_title %}

{% block top_buttons %}
    {% ticket_has_been_taken ticket=ticket as ticket_taken %}
    <div class="pb-md-4">
        <a role="button" class="btn btn-outline-secondary"
           href="{% url 'uni_ticket:user_dashboard' %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
            </svg> {% trans "Dashboard" %}
        </a>
        <a role="button" class="btn btn-outline-secondary"
           href="{% url 'uni_ticket:user_unassigned_ticket' %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-warning-circle"></use>
            </svg> {% trans "Torna alle richieste aperte" %}
        </a>
        <a role="button" class="btn btn-outline-secondary"
           href="{% url 'uni_ticket:user_opened_ticket' %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-clock"></use>
            </svg> {% trans "Torna alle richieste assegnate" %}
        </a>
        <a role="button" class="btn btn-outline-secondary"
           href="{% url 'uni_ticket:user_closed_ticket' %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
            </svg> {% trans "Torna alle richieste chiuse" %}
        </a>
    </div>

    {% if ticket.is_closed and not ticket.closed_by and not ticket.is_notification %}
    <button type="button"
        class="btn btn-outline-warning"
        data-bs-toggle="modal"
        data-bs-target="#reopenTicket">
        <svg class="icon icon-xs icon-warning">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-exchange-circle"></use>
        </svg> {% trans "Riapri richiesta" %}
    </button>
    <div class="modal fade" tabindex="-1" role="dialog" id="reopenTicket">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        {% trans "Riapertura richiesta" %}
                    </h5>
                    <button class="btn-close"
                            type="button"
                            data-bs-dismiss="modal"
                            aria-label="Close">
                       <svg class="icon">
                          <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                       </svg>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% trans "Vuoi davvero riaprire la richiesta" %}
                       <br>
                       <b>{{ ticket }}</b> ?
                    </p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'uni_ticket:user_reopen_ticket' ticket.code %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-warning" type="submit">
                            {% trans "Si, riapri la richiesta" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <a role="button"
       href="{% url 'uni_ticket:user_clone_ticket' ticket_id=ticket.code %}"
       class="btn btn-outline-secondary">
       <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-copy"></use>
       </svg> {% trans "Effettua richiesta simile" %}
    </a>

    {% if ticket_taken %}
        <a role="button" href="{% url 'uni_ticket:ticket_message' ticket_id=ticket.code %}"
           class="btn btn-outline-secondary">
            {% get_unread_messages ticket=ticket as unread_messages %}
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-comment"></use>
            </svg>
            {% if ticket_messages %}
            <span class="badge bg-primary">{% trans "Nuovi" %}</span>
            {% endif %}
            {% trans "Messaggi" %}
        </a>
    {% elif not ticket.is_closed and ticket_assignments.count == 1 and not ticket.protocol_number %}
        <a role="button"
           class="btn btn-outline-secondary"
           href="{% url 'uni_ticket:ticket_edit' ticket_id=ticket.code %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
            </svg> {% trans 'Modifica' %}
        </a>
    {% endif %}
    {% if not ticket.is_closed %}
        <a role="button"
           href="{% url 'uni_ticket:user_close_ticket' ticket_id=ticket.code %}"
           class="btn btn-outline-success">
            <svg class="icon icon-xs icon-success">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-check"></use>
            </svg> {% trans "Chiudi" %}
        </a>
    {% endif %}

    {% if not ticket_taken and not ticket.is_closed and ticket_assignments.count == 1 and not ticket.protocol_number %}
        <button type="button" class="btn btn-outline-danger"
                data-bs-toggle="modal"  data-bs-target="#modalCenter">
            <svg class="icon icon-xs icon-danger">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
            </svg> {% trans 'Elimina' %}
        </button>
        <div class="modal fade" tabindex="-1" role="dialog" id="modalCenter">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            {% trans "Richiesta conferma eliminazione" %}
                        </h5>
                        <button class="btn-close"
                                type="button"
                                data-bs-dismiss="modal"
                                aria-label="Close">
                           <svg class="icon">
                              <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                           </svg>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>{% trans "Vuoi davvero eliminare la richiesta" %}
                            <br>
                            <b>{{ ticket.code }}</b> ?
                        </p>
                    </div>
                    <div class="modal-footer">
                        <form action="{% url 'uni_ticket:ticket_delete' ticket_id=ticket.code %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">
                                {% trans "Si, elimina" %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock top_buttons %}

{% block page_content %}
    {% include 'ticket_detail.html' with is_simple_user=request.user %}
    {% include 'ticket_options.html' %}
{% endblock page_content %}

{% block extra_scripts %}
{{ block.super }}
<script>
document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach(el => {
    new bootstrap.Tooltip(el);
});
</script>
{% endblock %}

uniticket/uni_ticket_bootstrap_italia_template/templates/user/user_settings.html
{% extends "user_settings.html" %}

{% load i18n %}
{% load static %}

{% block menu_links %}
{% include 'user/main_menu.html' %}
{% endblock menu_links %}