uniticket/accounts/urls.py
from django.urls import path

from . settings import EDITABLE_FIELDS
from . views import changeData, confirmEmail


app_name = "accounts"

if EDITABLE_FIELDS:
    urlpatterns = [
        # url(r'^login/$', Login, name='login'),
        # path('logout', Logout, name='logout'),
        path('account/edit/', changeData, name='change_data'),
        path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),
    ]
else: # pragma: no cover
    urlpatterns = []

uniticket/api_rest/urls.py
from django.urls import path, re_path
from django.utils.text import slugify

from rest_framework import routers
from rest_framework.renderers import JSONOpenAPIRenderer
from rest_framework.schemas import get_schema_view

from api_rest.views import generic, manager, operator, user

from uni_ticket.settings import MANAGEMENT_URL_PREFIX


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', generic.UserViewSet)
router.register('groups', generic.GroupViewSet)

app_name = "api_rest"

urlpatterns = [
    # path('api/', include(router.urls)),
    # path('api-auth/', include(rest_framework.urls, 'rest_framework',)),

    re_path('^openapi/$',  get_schema_view(**{}), name='openapi-schema'),
    re_path('^openapi.json/$', get_schema_view(renderer_classes = [JSONOpenAPIRenderer], **{}), name='openapi-schema-json'),

    # generic
    path('api/strutture/list/', generic.TicketAPIStruttureList.as_view(), name='api-strutture-list'),
    path('api/ticket/category/list/', generic.TicketAPITicketCategoryList.as_view(),name='api-ticket-category-list'),

    # user
    path('api/<slug:structure_slug>/<slug:category_slug>/ticket/new/', user.TicketAPIView.as_view(), name='api-new-ticket'),
    path('api/ticket/<str:ticket_uid>/', user.TicketAPIDetail.as_view(), name='api-view-ticket'),
    path('api/ticket/user/list/', user.TicketAPIListCreated.as_view(), name='api-ticket-user-list'),
    path('api/ticket/close/<str:ticket_id>/', user.TicketAPIClose.as_view(), name='api-ticket-close'),

    # manager
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/unassigned/count/', manager.TicketAPIUnassignedCounter.as_view(), name='api-manager-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/open/count/', manager.TicketAPIOpenCounter.as_view(), name='api-manager-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/my-open/count/', manager.TicketAPIMyOpenCounter.as_view(), name='api-manager-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/messages/count/', manager.TicketAPIMessagesCounter.as_view(), name='api-manager-tickets-messages-count'),

    # operator
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/unassigned/count/', operator.TicketAPIUnassignedCounter.as_view(), name='api-operator-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/open/count/', operator.TicketAPIOpenCounter.as_view(), name='api-operator-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/my-open/count/', operator.TicketAPIMyOpenCounter.as_view(), name='api-operator-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/messages/count/', operator.TicketAPIMessagesCounter.as_view(), name='api-operator-tickets-messages-count'),
]

uniticket/app_io/urls.py
from django.urls import path

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from . views import *


app_name = "app_io"


base = f"{MANAGEMENT_URL_PREFIX['manager']}/<str:structure_slug>/categories/<str:category_slug>/app-io/services"


urlpatterns = [
    path(f'{base}/new/', new, name='app_io_services_new'),
    path(f'{base}/<int:service_id>/edit/', edit, name='app_io_services_edit'),
    path(f'{base}/<int:service_id>/enable/', enable, name='app_io_services_enable'),
    path(f'{base}/<int:service_id>/disable/', disable, name='app_io_services_disable'),
    path(f'{base}/<int:service_id>/delete/', delete, name='app_io_services_delete'),
]

uniticket/chat/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . api import ChatMessageModelViewSet, UserModelViewSet
from . import views

router = DefaultRouter()
router.register(r'message', ChatMessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')

app_name = "chat"

urlpatterns = [
    path(r'api/chat/', include(router.urls)),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('chat/random-vc-provider', views.random_vc_provider, name='random_vc_provider'),
]

uniticket/uni_ticket/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import path, re_path
from django.utils.text import slugify
from django.views.generic import RedirectView

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from .decorators import is_manager, is_operator, is_super_admin, is_the_owner
from .views import datatables, generic, management, manager, operator, user


app_name = "uni_ticket"

_dashboard_name = "dashboard"

# System/Generic URLs
# ticket = 'ticket/<str:ticket_id>'
ticket = "tickets/<str:ticket_id>"
urlpatterns = [
    path("", RedirectView.as_view(url="/{}/".format(_dashboard_name))),
    # Router url di responsabilità su struttura (manager/operator/user)
    re_path(
        r"^manage/(?:(?P<structure_slug>[-\w]+)(/)?)?$", generic.manage, name="manage"),
    # Attachments download
    path(
        "{}/download/attachment/<str:attachment>/".format(ticket),
        generic.download_attachment,
        name="download_attachment",
    ),
    path(
        "{}/messages/<str:reply_id>/download/attachment/".format(ticket),
        generic.download_message_attachment,
        name="download_message_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/attachment/".format(ticket),
        generic.download_task_attachment,
        name="download_task_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/closing-attachment/".format(ticket),
        generic.download_task_closing_attachment,
        name="download_task_closing_attachment",
    ),
    path(
        "<str:structure_slug>/<str:category_slug>/conditions/<int:condition_id>/download/attachment",
        generic.download_condition_attachment,
        name="download_condition_attachment",
    ),
    # Delete ticket message
    path(
        "messages/delete/<str:ticket_message_id>/",
        generic.ticket_message_delete,
        name="message_delete",
    ),
    path(
        "email-notify/update/", generic.email_notify_change, name="email_notify_change"
    ),
    path(
        "print/ticket/<str:ticket_id>/",
        user.ticket_detail_print,
        name="ticket_detail_print",
    ),
    path(
        "print/ticket/<str:ticket_id>/pdf/",
        user.download_ticket_pdf,
        name="ticket_detail_print_pdf",
    ),
]

# Datatables URLs
structure = "<str:structure_slug>"
urlpatterns += [
    # User json
    path(
        "user_all_tickets.json",
        datatables.user_all_tickets,
        name="user_all_tickets_json",
    ),
    path(
        "user_opened_ticket.json",
        datatables.user_opened_ticket,
        name="user_opened_ticket_json",
    ),
    path(
        "user_closed_ticket.json",
        datatables.user_closed_ticket,
        name="user_closed_ticket_json",
    ),
    path(
        "user_unassigned_ticket.json",
        datatables.user_unassigned_ticket,
        name="user_unassigned_ticket_json",
    ),
    # Manager json
    path(
        "{}/manager_unassigned_ticket.json".format(structure),
        datatables.manager_unassigned_ticket,
        name="manager_unassigned_ticket_json",
    ),
    path(
        "{}/manager_opened_ticket.json".format(structure),
        datatables.manager_opened_ticket,
        name="manager_opened_ticket_json",
    ),
    path(
        "{}/my/manager_opened_ticket.json".format(structure),
        datatables.manager_my_opened_ticket,
        name="manager_my_opened_ticket_json",
    ),
    path(
        "{}/manager_closed_ticket.json".format(structure),
        datatables.manager_closed_ticket,
        name="manager_closed_ticket_json",
    ),
    path(
        "{}/manager_all_tickets.json".format(structure),
        datatables.manager_all_tickets,
        name="manager_all_tickets_json",
    ),
    # Operator json
    path(
        "{}/operator_unassigned_ticket.json".format(structure),
        datatables.operator_unassigned_ticket,
        name="operator_unassigned_ticket_json",
    ),
    path(
        "{}/operator_opened_ticket.json".format(structure),
        datatables.operator_opened_ticket,
        name="operator_opened_ticket_json",
    ),
    path(
        f"{structure}/my/operator_opened_ticket.json",
        datatables.operator_my_opened_ticket,
        name="operator_my_opened_ticket_json",
    ),
    path(
        f"{structure}/operator_closed_ticket.json",
        datatables.operator_closed_ticket,
        name="operator_closed_ticket_json",
    ),
    path(
        f"{structure}/operator_all_tickets.json",
        datatables.operator_all_tickets,
        name="operator_all_tickets_json",
    ),
]

# Management URLs (manager and operator)
base = "manage/<str:structure_slug>"
tickets = "{}/tickets".format(base)
# ticket = '{}'.format(tickets)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)

urlpatterns += [
    # Export CSV
    # path('{}/export-csv/'.format(tickets), management.export_category_csv, name='export_category_csv'),
    # Export csv/zip
    path(
        "{}/export_detailed_report/".format(tickets),
        management.export_detailed_report,
        name="manage_export_detailed_report",
    ),
    # Tickets
    path(
        "{}/opened/".format(tickets),
        management.manage_opened_ticket_url,
        name="manage_opened_ticket_url",
    ),
    path(
        "{}/unassigned/".format(tickets),
        management.manage_unassigned_ticket_url,
        name="manage_unassigned_ticket_url",
    ),
    path(
        "{}/closed/".format(tickets),
        management.manage_closed_ticket_url,
        name="manage_closed_ticket_url",
    ),
    path(
        "{}/".format(tickets),
        management.manage_not_closed_ticket_url,
        name="manage_not_closed_ticket_url",
    ),
    path("{}/".format(tickets), management.manage_ticket_url,
         name="manage_ticket_url"),
    path(
        "{}/".format(ticket_id),
        management.manage_ticket_url_detail,
        name="manage_ticket_url_detail",
    ),
    path(
        "{}/messages/".format(ticket_id),
        management.ticket_message_url,
        name="manage_ticket_message_url",
    ),
    path(
        "{}/notes/".format(ticket_id),
        management.ticket_notes_url,
        name="manage_ticket_notes_url",
    ),
    path(
        "{}/notes/<int:note_id>/".format(ticket_id),
        management.ticket_note_url,
        name="manage_ticket_note_url",
    ),
    path(
        "{}/notes/<str:note_id>/delete/".format(ticket_id),
        management.ticket_note_delete,
        name="manage_ticket_note_delete",
    ),
    path(
        "{}/competence/add/".format(ticket_id),
        management.ticket_competence_add_url,
        name="add_ticket_competence_url",
    ),
    path(
        "{}/competence/leave/".format(ticket_id),
        management.ticket_competence_leave,
        name="leave_ticket_competence",
    ),
    path(
        "{}/dependence/add/".format(ticket_id),
        management.ticket_dependence_add_url,
        name="add_ticket_dependence_url",
    ),
    path(
        "{}/dependence/remove/<str:main_ticket_id>/".format(ticket_id),
        management.ticket_dependence_remove,
        name="remove_ticket_dependence",
    ),
    path(
        "{}/close/".format(ticket_id), management.ticket_close_url, name="close_ticket"
    ),
    path(
        "{}/reopen/".format(ticket_id), management.ticket_reopen, name="reopen_ticket"
    ),
    path(
        "{}/assign-offices/".format(ticket_id),
        management.ticket_taken_by_unassigned_offices,
        name="ticket_taken_by_unassigned_offices",
    ),
    # path('{}/assign/<str:destination_structure_slug>/<str:office_slug>/'.format(ticket_id), management.ticket_taken_by_unassigned_office, name='ticket_taken_by_unassigned_office'),
    # Task
    path(
        "{}/add/".format(task), management.task_add_new_url, name="add_ticket_task_url"
    ),
    path(
        "{}/".format(task_id), management.task_detail_url, name="manage_task_detail_url"
    ),
    path("{}/close/".format(task_id),
         management.task_close_url, name="close_task"),
    path("{}/delete/".format(task_id),
         management.task_remove, name="task_remove"),
    path("{}/riapri/".format(task_id),
         management.task_reopen, name="reopen_task"),
    path(
        "{}/edit/remove-attachment/".format(task_id),
        management.task_attachment_delete,
        name="manage_elimina_allegato_task",
    ),
    path("{}/edit/".format(task_id), management.task_edit_url, name="edit_task"),
]

# Manager URLs
base = "{}/<str:structure_slug>".format(
    slugify(MANAGEMENT_URL_PREFIX["manager"]))
tickets = "{}/tickets".format(base)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)
offices = "{}/offices".format(base)
office = "{}/office".format(offices)
office_id = "{}/<str:office_slug>".format(office)
categories = "{}/categories".format(base)
# category = '{}/category'.format(categories)
category_id = "{}/<str:category_slug>".format(categories)
cat_input = "{}/input".format(category_id)
cat_input_id = "{}/<int:module_id>".format(cat_input)
condition = "{}/conditions".format(category_id)
condition_id = "{}/<int:condition_id>".format(condition)
default_reply = "{}/default_replies".format(category_id)
default_reply_id = "{}/<int:default_reply_id>".format(default_reply)
category_task = "{}/default-tasks".format(category_id)
category_task_id = "{}/<str:task_id>".format(category_task)

structure_protocol_configurations = "{}/settings/protocol-configurations".format(
    base)
structure_protocol_configuration = "{}/<int:configuration_id>".format(
    structure_protocol_configurations
)

category_protocol_configurations = "{}/protocol-configurations".format(
    category_id)
category_protocol_configuration = "{}/<int:configuration_id>".format(
    category_protocol_configurations
)

urlpatterns += [
    path(

uniticket/uni_ticket/views/operator.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from organizational_area.models import *

from uni_ticket.decorators import is_operator
from uni_ticket.models import *
from uni_ticket.settings import OPERATOR_PREFIX
from uni_ticket.utils import base_context, user_offices_list, visible_tickets_to_user


@login_required
@is_operator
def dashboard(request, structure_slug, structure, office_employee):
    """
    Operator Dashboard

    :type structure_slug: String
    :type structure: OrganizationalStructure (from @is_operator)
    :type office_employee: OrganizationalStructureOfficeEmployee (from @is_operator)

    :param structure_slug: structure slug
    :param structure: structure object (from @is_operator)
    :param office_employee: employe offices queryset (from @is_operator)

    :return: render
    """
    title = _("Pannello di Controllo")
    sub_title = _("Gestisci le richieste in modalità {}").format(
        OPERATOR_PREFIX)
    template = "operator/dashboard.html"
    offices = user_offices_list(office_employee)

    d = {
        "offices": offices,
        "structure": structure,
        "sub_title": sub_title,
        "title": title,
        # "ticket_messages": messages,
    }
    return render(request, template, base_context(d))

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/add_ticket_competence.html
{% extends "management/add_ticket_competence.html" %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/add_ticket_task.html
{% extends "management/add_ticket_task.html" %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/counters.html
{% load i18n %}
{% load static %}


<div id="counters">
    <div class="d-none d-md-block">
        <a role="button"
           class="btn btn-outline-secondary me-1"
           href="{% url 'uni_ticket:manage_unassigned_ticket_url' structure_slug=structure.slug %}">
            <span class="badge bg-info" v-if="unassigned != null">[[ unassigned ]]</span>
            <div class="spinner-border spinner-border-sm" role="status" v-else>
                <span class="visually-hidden">In elaborazione...</span>
            </div>
            {% trans 'Aperte' %}
        </a>
        <a role="button" class="btn btn-outline-secondary me-1" href="{% url 'uni_ticket:manage_opened_ticket_url' structure_slug=structure.slug %}">
            <span class="badge bg-info" v-if="open != null">
                [[ open ]]
            </span>
            <div class="spinner-border spinner-border-sm" role="status" v-else>
                <span class="visually-hidden">In elaborazione...</span>
            </div>
            {% trans 'Assegnate' %}
            <span class="badge bg-info" v-if="my_open != null">([[ my_open ]] {% trans 'a me' %})</span>
        </a>
        <a role="button" class="btn btn-outline-secondary me-1" href="{% url 'uni_ticket:manage_closed_ticket_url' structure_slug=structure.slug %}">
            {% trans 'Chiuse' %}
        </a>
        <a role="button" class="btn btn-outline-secondary" href="{% url 'uni_ticket:operator_messages' structure_slug=structure.slug %}">
            <div class="spinner-border spinner-border-sm" role="status" v-if="new_messages == null">
                <span class="visually-hidden">In elaborazione...</span>
            </div>
            <svg class="icon icon-xs" v-else>
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-comment"></use>
            </svg>
            <span class="badge bg-primary" v-if="new_messages">{% trans "Nuovi" %}</span>
            {% trans 'Messaggi' %}
        </a>
    </div>
    <div class="d-block d-md-none">
        <nav class="toolbar">
            <ul>
                <li>
                    <a href="{% url 'uni_ticket:manage_unassigned_ticket_url' structure_slug=structure.slug %}">
                        <div class="badge-wrapper" v-if="unassigned">
                            <span class="toolbar-badge bg-primary">
                                [[ unassigned ]]
                            </span>
                        </div>
                        <svg class="icon"><use xlink:href="{% static 'svg/sprites.svg' %}#it-warning-circle"></use></svg>
                        <span class="toolbar-label">{% trans 'Aperte' %}</span></span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'uni_ticket:manage_opened_ticket_url' structure_slug=structure.slug %}">
                        <div class="badge-wrapper" v-if="open">
                            <span class="toolbar-badge bg-primary">
                                [[ open ]]
                            </span>
                        </div>
                        <svg class="icon"><use xlink:href="{% static 'svg/sprites.svg' %}#it-clock"></use></svg>
                        <span class="toolbar-label">{% trans 'Assegnate' %}
                            <span v-if="my_open"><br>([[ my_open ]] {% trans 'a me' %})</span>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'uni_ticket:manage_closed_ticket_url' structure_slug=structure.slug %}">
                        <svg class="icon"><use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use></svg>
                        <span class="toolbar-label">{% trans 'Chiuse' %}</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'uni_ticket:operator_messages' structure_slug=structure.slug %}">
                        <div class="badge-wrapper" v-if="new_messages">
                            <span class="toolbar-badge bg-primary">
                                {% trans "Nuovi" %}
                            </span>
                        </div>
                        <svg class="icon">
                            <use xlink:href="{% static 'svg/sprites.svg' %}#it-comment"></use>
                        </svg>
                        <span class="toolbar-label">{% trans 'Messaggi' %}</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
<script>
const app = Vue.createApp({
    delimiters: ['[[', ']]'],
    data () {
        return {
            unassigned: null,
            open: null,
            my_open: null,
            new_messages: false
        }
    },
    created(){
        this.interval = setInterval(() =>{
            this.getUnassigned();
            this.getOpen();
            this.getMyOpen();
            this.getMessages();
            }, 20000)
    },
    destroyed(){
        clearInterval(this.interval)
    },
    mounted () {
        this.getUnassigned()
        this.getOpen()
        this.getMyOpen()
        this.getMessages()
    },
    methods: {
        getUnassigned() {
            api_url = '{% url "api_rest:api-operator-tickets-unassigned-count" structure_slug=structure.slug %}'
            axios
                .get(api_url)
                .then(response => {
                    this.unassigned = response.data.count
                })
        },
        getOpen() {
            api_url = '{% url "api_rest:api-operator-tickets-open-count" structure_slug=structure.slug %}'
            axios
                .get(api_url)
                .then(response => {
                    this.open = response.data.count
                })
        },
        getMyOpen() {
            api_url = '{% url "api_rest:api-operator-tickets-my-open-count" structure_slug=structure.slug %}'
            axios
                .get(api_url)
                .then(response => {
                    this.my_open = response.data.count
                })
        },
        getMessages() {
            api_url = '{% url "api_rest:api-operator-tickets-messages-count" structure_slug=structure.slug %}'
            axios
                .get(api_url)
                .then(response => {
                    this.new_messages = response.data.count
                })
        }
    }
}).mount('#counters')
</script>

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/dashboard.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load uni_ticket_tags %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

{% block container_inner %}

{% app_is_installed "chat" as chat_installed %}
{% app_is_installed "channels" as channels_installed %}
{% user_operator_chat request.user structure as user_operator_chat %}

<div class="pb-4 clearfix">
    <div class="pull-start">
        {% include 'operator/counters.html' %}
    </div>
    {% if chat_installed and channels_installed and user_operator_chat %}
    <div class="pull-end">
        <a role="button"
          class="btn btn-outline-success"
          href="{% url 'chat:room' room_name=structure.slug %}">
            <svg class="icon icon-xs icon-success">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-user"></use>
            </svg> {% trans "Entra in Chat" %}
        </a>
    </div>
    {% endif %}
</div>
<hr />
<h5 class="py-3">{% trans "Uffici di afferenza" %}</h5>
{% include 'operator/offices_list.html' %}
{% endblock container_inner %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/opened_ticket.html
{% extends "base_page_schema.html" %}

{% load i18n %}
{% load static %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

{% block top_buttons %}
<a role="button" class="btn btn-outline-secondary"
   href="{% url 'uni_ticket:manage' structure_slug=structure.slug %}">
    <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
    </svg> {% trans "Dashboard" %}
</a>
<a role="button" class="btn btn-outline-secondary"
   href="{% url 'uni_ticket:operator_tickets' structure_slug=structure.slug %}">
    <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
    </svg> {% trans "Torna a tutte le richieste" %}
</a>
    {% block my_tickets_button %}
    <a role="button" class="btn btn-outline-secondary"
       href="{% url 'uni_ticket:operator_my_opened_ticket' structure_slug=structure.slug %}">
        <svg class="icon icon-xs">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-user"></use>
        </svg> {% trans "Vedi richieste assegnate a me" %}
    </a>
    {% endblock my_tickets_button %}
{% endblock top_buttons %}

{% block page_content %}
{% include 'datatables/table.html' %}
{% endblock page_content %}


{% block extra_scripts %}
{% url 'uni_ticket:manage_ticket_url' structure.slug as var_url %}
{% url 'uni_ticket:operator_opened_ticket_json' structure.slug as ajax_url %}
{% include 'datatables/datatable_script.html' with var_url=var_url ajax_url=ajax_url %}
{% endblock extra_scripts %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/task_detail.html
{% extends "management/task_detail.html" %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/task_edit.html
{% extends "management/task_edit.html" %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/ticket_assistance.html
{% extends "base_page_schema.html" %}

{% load i18n %}
{% load static %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

{% block top_buttons %}
<a role="button" class="btn btn-outline-secondary"
   href="{% url 'uni_ticket:manage_ticket_url_detail' structure.slug ticket.code %}">
    <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
    </svg> {% trans 'Torna alla richiesta' %}
</a>
<a role="button" class="btn btn-outline-secondary"
   href="{% url 'uni_ticket:operator_messages' structure_slug=structure.slug %}">
   <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-comment"></use>
    </svg> {% trans 'Tutti i messaggi' %}
</a>
{% endblock top_buttons %}

{% block clean_content %}
{% include "ticket_assistance.html" with management=True %}
{% endblock clean_content %}

{% block extra_scripts %}
{{ form.media }}
{% endblock extra_scripts %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/ticket_detail.html
{% extends "management/ticket_detail.html" %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

uniticket/uni_ticket_bootstrap_italia_template/templates/operator/tickets.html
{% extends "base_page_schema.html" %}

{% load i18n %}
{% load static %}

{% block menu_links %}
{% include 'operator/main_menu.html' %}
{% endblock menu_links %}

{% block top_buttons %}
{% include 'operator/counters.html' %}
{% endblock top_buttons %}

{% block page_content %}
{% include 'datatables/table.html' %}
{% endblock page_content %}

{% block extra_scripts %}
{% url 'uni_ticket:manage_ticket_url' structure.slug as var_url %}
{% url 'uni_ticket:operator_all_tickets_json' structure.slug as ajax_url %}
{% include 'datatables/datatable_script.html' with var_url=var_url ajax_url=ajax_url %}
{% endblock extra_scripts %}