uniticket/accounts/urls.py
from django.urls import path

from . settings import EDITABLE_FIELDS
from . views import changeData, confirmEmail


app_name = "accounts"

if EDITABLE_FIELDS:
    urlpatterns = [
        # url(r'^login/$', Login, name='login'),
        # path('logout', Logout, name='logout'),
        path('account/edit/', changeData, name='change_data'),
        path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),
    ]
else: # pragma: no cover
    urlpatterns = []

uniticket/api_rest/urls.py
from django.urls import path, re_path
from django.utils.text import slugify

from rest_framework import routers
from rest_framework.renderers import JSONOpenAPIRenderer
from rest_framework.schemas import get_schema_view

from api_rest.views import generic, manager, operator, user

from uni_ticket.settings import MANAGEMENT_URL_PREFIX


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', generic.UserViewSet)
router.register('groups', generic.GroupViewSet)

app_name = "api_rest"

urlpatterns = [
    # path('api/', include(router.urls)),
    # path('api-auth/', include(rest_framework.urls, 'rest_framework',)),

    re_path('^openapi/$',  get_schema_view(**{}), name='openapi-schema'),
    re_path('^openapi.json/$', get_schema_view(renderer_classes = [JSONOpenAPIRenderer], **{}), name='openapi-schema-json'),

    # generic
    path('api/strutture/list/', generic.TicketAPIStruttureList.as_view(), name='api-strutture-list'),
    path('api/ticket/category/list/', generic.TicketAPITicketCategoryList.as_view(),name='api-ticket-category-list'),

    # user
    path('api/<slug:structure_slug>/<slug:category_slug>/ticket/new/', user.TicketAPIView.as_view(), name='api-new-ticket'),
    path('api/ticket/<str:ticket_uid>/', user.TicketAPIDetail.as_view(), name='api-view-ticket'),
    path('api/ticket/user/list/', user.TicketAPIListCreated.as_view(), name='api-ticket-user-list'),
    path('api/ticket/close/<str:ticket_id>/', user.TicketAPIClose.as_view(), name='api-ticket-close'),

    # manager
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/unassigned/count/', manager.TicketAPIUnassignedCounter.as_view(), name='api-manager-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/open/count/', manager.TicketAPIOpenCounter.as_view(), name='api-manager-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/my-open/count/', manager.TicketAPIMyOpenCounter.as_view(), name='api-manager-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/messages/count/', manager.TicketAPIMessagesCounter.as_view(), name='api-manager-tickets-messages-count'),

    # operator
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/unassigned/count/', operator.TicketAPIUnassignedCounter.as_view(), name='api-operator-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/open/count/', operator.TicketAPIOpenCounter.as_view(), name='api-operator-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/my-open/count/', operator.TicketAPIMyOpenCounter.as_view(), name='api-operator-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/messages/count/', operator.TicketAPIMessagesCounter.as_view(), name='api-operator-tickets-messages-count'),
]

uniticket/app_io/urls.py
from django.urls import path

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from . views import *


app_name = "app_io"


base = f"{MANAGEMENT_URL_PREFIX['manager']}/<str:structure_slug>/categories/<str:category_slug>/app-io/services"


urlpatterns = [
    path(f'{base}/new/', new, name='app_io_services_new'),
    path(f'{base}/<int:service_id>/edit/', edit, name='app_io_services_edit'),
    path(f'{base}/<int:service_id>/enable/', enable, name='app_io_services_enable'),
    path(f'{base}/<int:service_id>/disable/', disable, name='app_io_services_disable'),
    path(f'{base}/<int:service_id>/delete/', delete, name='app_io_services_delete'),
]

uniticket/chat/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . api import ChatMessageModelViewSet, UserModelViewSet
from . import views

router = DefaultRouter()
router.register(r'message', ChatMessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')

app_name = "chat"

urlpatterns = [
    path(r'api/chat/', include(router.urls)),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('chat/random-vc-provider', views.random_vc_provider, name='random_vc_provider'),
]

uniticket/uni_ticket/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import path, re_path
from django.utils.text import slugify
from django.views.generic import RedirectView

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from .decorators import is_manager, is_operator, is_super_admin, is_the_owner
from .views import datatables, generic, management, manager, operator, user


app_name = "uni_ticket"

_dashboard_name = "dashboard"

# System/Generic URLs
# ticket = 'ticket/<str:ticket_id>'
ticket = "tickets/<str:ticket_id>"
urlpatterns = [
    path("", RedirectView.as_view(url="/{}/".format(_dashboard_name))),
    # Router url di responsabilità su struttura (manager/operator/user)
    re_path(
        r"^manage/(?:(?P<structure_slug>[-\w]+)(/)?)?$", generic.manage, name="manage"),
    # Attachments download
    path(
        "{}/download/attachment/<str:attachment>/".format(ticket),
        generic.download_attachment,
        name="download_attachment",
    ),
    path(
        "{}/messages/<str:reply_id>/download/attachment/".format(ticket),
        generic.download_message_attachment,
        name="download_message_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/attachment/".format(ticket),
        generic.download_task_attachment,
        name="download_task_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/closing-attachment/".format(ticket),
        generic.download_task_closing_attachment,
        name="download_task_closing_attachment",
    ),
    path(
        "<str:structure_slug>/<str:category_slug>/conditions/<int:condition_id>/download/attachment",
        generic.download_condition_attachment,
        name="download_condition_attachment",
    ),
    # Delete ticket message
    path(
        "messages/delete/<str:ticket_message_id>/",
        generic.ticket_message_delete,
        name="message_delete",
    ),
    path(
        "email-notify/update/", generic.email_notify_change, name="email_notify_change"
    ),
    path(
        "print/ticket/<str:ticket_id>/",
        user.ticket_detail_print,
        name="ticket_detail_print",
    ),
    path(
        "print/ticket/<str:ticket_id>/pdf/",
        user.download_ticket_pdf,
        name="ticket_detail_print_pdf",
    ),
]

# Datatables URLs
structure = "<str:structure_slug>"
urlpatterns += [
    # User json
    path(
        "user_all_tickets.json",
        datatables.user_all_tickets,
        name="user_all_tickets_json",
    ),
    path(
        "user_opened_ticket.json",
        datatables.user_opened_ticket,
        name="user_opened_ticket_json",
    ),
    path(
        "user_closed_ticket.json",
        datatables.user_closed_ticket,
        name="user_closed_ticket_json",
    ),
    path(
        "user_unassigned_ticket.json",
        datatables.user_unassigned_ticket,
        name="user_unassigned_ticket_json",
    ),
    # Manager json
    path(
        "{}/manager_unassigned_ticket.json".format(structure),
        datatables.manager_unassigned_ticket,
        name="manager_unassigned_ticket_json",
    ),
    path(
        "{}/manager_opened_ticket.json".format(structure),
        datatables.manager_opened_ticket,
        name="manager_opened_ticket_json",
    ),
    path(
        "{}/my/manager_opened_ticket.json".format(structure),
        datatables.manager_my_opened_ticket,
        name="manager_my_opened_ticket_json",
    ),
    path(
        "{}/manager_closed_ticket.json".format(structure),
        datatables.manager_closed_ticket,
        name="manager_closed_ticket_json",
    ),
    path(
        "{}/manager_all_tickets.json".format(structure),
        datatables.manager_all_tickets,
        name="manager_all_tickets_json",
    ),
    # Operator json
    path(
        "{}/operator_unassigned_ticket.json".format(structure),
        datatables.operator_unassigned_ticket,
        name="operator_unassigned_ticket_json",
    ),
    path(
        "{}/operator_opened_ticket.json".format(structure),
        datatables.operator_opened_ticket,
        name="operator_opened_ticket_json",
    ),
    path(
        f"{structure}/my/operator_opened_ticket.json",
        datatables.operator_my_opened_ticket,
        name="operator_my_opened_ticket_json",
    ),
    path(
        f"{structure}/operator_closed_ticket.json",
        datatables.operator_closed_ticket,
        name="operator_closed_ticket_json",
    ),
    path(
        f"{structure}/operator_all_tickets.json",
        datatables.operator_all_tickets,
        name="operator_all_tickets_json",
    ),
]

# Management URLs (manager and operator)
base = "manage/<str:structure_slug>"
tickets = "{}/tickets".format(base)
# ticket = '{}'.format(tickets)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)

urlpatterns += [
    # Export CSV
    # path('{}/export-csv/'.format(tickets), management.export_category_csv, name='export_category_csv'),
    # Export csv/zip
    path(
        "{}/export_detailed_report/".format(tickets),
        management.export_detailed_report,
        name="manage_export_detailed_report",
    ),
    # Tickets
    path(
        "{}/opened/".format(tickets),
        management.manage_opened_ticket_url,
        name="manage_opened_ticket_url",
    ),
    path(
        "{}/unassigned/".format(tickets),
        management.manage_unassigned_ticket_url,
        name="manage_unassigned_ticket_url",
    ),
    path(
        "{}/closed/".format(tickets),
        management.manage_closed_ticket_url,
        name="manage_closed_ticket_url",
    ),
    path(
        "{}/".format(tickets),
        management.manage_not_closed_ticket_url,
        name="manage_not_closed_ticket_url",
    ),
    path("{}/".format(tickets), management.manage_ticket_url,
         name="manage_ticket_url"),
    path(
        "{}/".format(ticket_id),
        management.manage_ticket_url_detail,
        name="manage_ticket_url_detail",
    ),
    path(
        "{}/messages/".format(ticket_id),
        management.ticket_message_url,
        name="manage_ticket_message_url",
    ),
    path(
        "{}/notes/".format(ticket_id),
        management.ticket_notes_url,
        name="manage_ticket_notes_url",
    ),
    path(
        "{}/notes/<int:note_id>/".format(ticket_id),
        management.ticket_note_url,
        name="manage_ticket_note_url",
    ),
    path(
        "{}/notes/<str:note_id>/delete/".format(ticket_id),
        management.ticket_note_delete,
        name="manage_ticket_note_delete",
    ),
    path(
        "{}/competence/add/".format(ticket_id),
        management.ticket_competence_add_url,
        name="add_ticket_competence_url",
    ),
    path(
        "{}/competence/leave/".format(ticket_id),
        management.ticket_competence_leave,
        name="leave_ticket_competence",
    ),
    path(
        "{}/dependence/add/".format(ticket_id),
        management.ticket_dependence_add_url,
        name="add_ticket_dependence_url",
    ),
    path(
        "{}/dependence/remove/<str:main_ticket_id>/".format(ticket_id),
        management.ticket_dependence_remove,
        name="remove_ticket_dependence",
    ),
    path(
        "{}/close/".format(ticket_id), management.ticket_close_url, name="close_ticket"
    ),
    path(
        "{}/reopen/".format(ticket_id), management.ticket_reopen, name="reopen_ticket"
    ),
    path(
        "{}/assign-offices/".format(ticket_id),
        management.ticket_taken_by_unassigned_offices,
        name="ticket_taken_by_unassigned_offices",
    ),
    # path('{}/assign/<str:destination_structure_slug>/<str:office_slug>/'.format(ticket_id), management.ticket_taken_by_unassigned_office, name='ticket_taken_by_unassigned_office'),
    # Task
    path(
        "{}/add/".format(task), management.task_add_new_url, name="add_ticket_task_url"
    ),
    path(
        "{}/".format(task_id), management.task_detail_url, name="manage_task_detail_url"
    ),
    path("{}/close/".format(task_id),
         management.task_close_url, name="close_task"),
    path("{}/delete/".format(task_id),
         management.task_remove, name="task_remove"),
    path("{}/riapri/".format(task_id),
         management.task_reopen, name="reopen_task"),
    path(
        "{}/edit/remove-attachment/".format(task_id),
        management.task_attachment_delete,
        name="manage_elimina_allegato_task",
    ),
    path("{}/edit/".format(task_id), management.task_edit_url, name="edit_task"),
]

# Manager URLs
base = "{}/<str:structure_slug>".format(
    slugify(MANAGEMENT_URL_PREFIX["manager"]))
tickets = "{}/tickets".format(base)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)
offices = "{}/offices".format(base)
office = "{}/office".format(offices)
office_id = "{}/<str:office_slug>".format(office)
categories = "{}/categories".format(base)
# category = '{}/category'.format(categories)
category_id = "{}/<str:category_slug>".format(categories)
cat_input = "{}/input".format(category_id)
cat_input_id = "{}/<int:module_id>".format(cat_input)
condition = "{}/conditions".format(category_id)
condition_id = "{}/<int:condition_id>".format(condition)
default_reply = "{}/default_replies".format(category_id)
default_reply_id = "{}/<int:default_reply_id>".format(default_reply)
category_task = "{}/default-tasks".format(category_id)
category_task_id = "{}/<str:task_id>".format(category_task)

structure_protocol_configurations = "{}/settings/protocol-configurations".format(
    base)
structure_protocol_configuration = "{}/<int:configuration_id>".format(
    structure_protocol_configurations
)

category_protocol_configurations = "{}/protocol-configurations".format(
    category_id)
category_protocol_configuration = "{}/<int:configuration_id>".format(
    category_protocol_configurations
)

urlpatterns += [
    path(

uniticket/uni_ticket_bootstrap_italia_template/templates/custom_message.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block header_slim_right_zone %}{% endblock header_slim_right_zone %}

{% block container_inner %}
{% block content_title %}{% endblock content_title %}
<div class="callout danger mt-5">
    <div class="callout-inner">
        <div class="callout-title">
            <svg class="icon icon-primary icon-danger">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
            </svg>
            <span class="text">{% trans "Oops! C'è qualcosa che non va" %}</span>
        </div>
        <p>
            {{ avviso }}
            <hr>
            <a role="button" class="btn btn-outline-secondary"
               href="javascript:history.back()">
                {% trans "Torna indietro" %}
            </a>
            <a role="button" class="btn btn-outline-secondary"
               href="{% url 'uni_ticket:manage' structure_slug=structure_slug %}">
                {% trans "Torna alla Dashboard" %}
            </a>
        </p>
    </div>
</div>
{% endblock container_inner %}

uniticket/uni_ticket_bootstrap_italia_template/templates/email-toggle-notify.html
{% load i18n %}
{% load static %}

{% if request.user.email %}
<div class="row">
    <div class="col">
        <div class="card-wrapper card-space pb-3">
            <div class="card card-bg no-after">
                <div class="card-body">
                    <div id="email-notify-message"></div>
                    <form>
                        <div class="form-check form-check-group">
                            <div class="toggles">
                              <label for="notifyEmail">
                                    <svg class="icon icon-xs">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-mail"></use>
                                    </svg> {% trans "Notifiche e-mail" %}

                                <input type="checkbox"
                                       ic-post-to="{% url 'uni_ticket:email_notify_change' %}"
                                       ic-target="#email-notify-message"
                                       ic-select-from-response="#intercooler-notify"
                                       id="notifyEmail"
                                       aria-labelledby="notify-email-help"
                                       {% if request.user.email_notify %}
                                       checked
                                       {% endif %}
                                        >
                                <span class="lever"></span>
                              </label>
                            </div>
                            <small id="notify-email-help" class="form-text">
                                    {% trans "Se attiva, questa funzione invierà sulla mail" %}
                                    <b>{{ request.user.email }}</b>
                                    {% trans "le notifiche inerenti alle tue richieste e un rapporto periodico di riepilogo." %}
                                    {% trans "Disattivandola, non verrà recapitato alcun messaggio." %}
                            </small>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
   </div>
</div>
{% else %}
<div class="alert alert-warning alert-dismissible fade show mb-4" role="alert">
     {% trans "Nessun indirizzo e-mail associato alla tua utenza." %}
    {% trans "Contatta il supporto tecnico per risolvere il problema." %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
    </button>
</div>
{% endif %}

uniticket/uni_ticket_bootstrap_italia_template/templates/intercooler-notify.html
{% load i18n %}
{% load static %}

<div id="intercooler-notify">
    {% if data.error %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ data.error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
          </button>
    </div>
    {% elif data.email %}
        {% if data.notify_status %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
            {% trans "Notifiche abilitate sulla mail:" %} <b>{{ data.email }}</b>
        {% else %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% trans "Notifiche disabilitate sulla mail:" %} <b>{{ data.email }}</b>
        {% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
        </button>
    </div>
    {% endif %}
</div>

uniticket/uni_ticket_bootstrap_italia_template/templates/logs.html
{% load i18n %}
{% load static %}
{% load uni_ticket_tags %}

<div class="it-list-wrapper">
    {% if logs %}
    <ul class="it-list">
    {% for log in logs %}
        <li>
            <div class="list-item">
                <div class="row it-right-zone">
                    <div class="col-12 col-lg-6 text">
                        {{ log.change_message|linebreaksbr }}
                        {% if log.app_io_message %}
                            <br>
                            <img src="{% static 'images/io-it-logo.svg' %}" width="20"/>
                            <small>
                                {% if log.app_io_message.response.error %}
                                <svg class="icon icon-danger" style="width: 20px" aria-labelledby="{{ log.pk }}-error">
                                    <title id="{{ log.pk }}-error">
                                        {{ log.app_io_message.response.error }}
                                    </title>
                                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-error"></use>
                                </svg> Notifica tramite App IO fallita. Errore: {{ log.app_io_message.response.error }}
                                {% else %}
                                <svg class="icon icon-success" style="width: 20px" aria-labelledby="{{ log.pk }}-success">
                                    <title id="{{ log.pk }}-success">
                                        ID messaggio: {{ log.app_io_message.response.message_id }}
                                    </title>
                                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
                                </svg> Notifica inviata tramite App IO
                                {% endif %}
                            </small>
                        {% endif %}
                    </div>
                    <div class="col-12 col-lg-6 it-multiple">
                        <span class="text-start text-lg-end metadata">
                            {% trans "Operatore" %} {{ log.user.pk }}
                            <br>
                            {{ log.action_time }}
                        </span>
                    </div>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
    {% else %}
        {% trans "Nessun log" %}
    {% endif %}
</div>

uniticket/uni_ticket_bootstrap_italia_template/templates/ticket_detail_category_conditions.html
{% load i18n %}
{% load static %}
{% load uni_ticket_tags %}


{% if ticket.input_module.ticket_category.show_heading_text %}
<p class="card-title text-start">
    {% uni_ticket_settings_value name="TICKET_HEADING_TEXT" user=ticket.created_by taxpayer=ticket.created_by.taxpayer_id category=ticket.input_module.ticket_category as heading %}
    {{ heading|safe  }}
    {% uni_ticket_settings_value "EMPLOYEE_ATTRIBUTE_NAME" as employee_attribute_name %}
    {% uni_ticket_settings_value "EMPLOYEE_ATTRIBUTE_LABEL" as employee_attribute_label %}
    {% obj_get_attr ticket.created_by employee_attribute_name as user_employee_attribute %}
    {% if user_employee_attribute %}
        <br><span class="small"><b>{{ employee_attribute_label }}</b>: {{user_employee_attribute}}</span>
    {% endif %}
    {% uni_ticket_settings_value "USER_ATTRIBUTE_NAME" as user_attribute_name %}
    {% uni_ticket_settings_value "USER_ATTRIBUTE_LABEL" as user_attribute_label %}
    {% obj_get_attr ticket.created_by user_attribute_name as user_user_attribute %}
    {% if user_user_attribute %}
        <br><span class="small"><b>{{ user_attribute_label }}</b>: {{user_user_attribute}}</span>
    {% endif %}
</p>
<hr>
{% endif %}
{% for condition in category_conditions %}
{% if not forloop.first %}<hr>{% endif %}
<h6>{{ condition.title }}</h6>
<p class="card-text">{{ condition.text | markdown | safe }}</p>
{% if condition.attachment %}
<a href="{% url 'uni_ticket:download_condition_attachment' structure_slug=condition.category.organizational_structure.slug category_slug=condition.category.slug condition_id=condition.pk %}">
        <svg class="icon">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-clip"></use>
        </svg>{{ condition.attachment|filename }}
    </a>
{% endif %}
{% endfor %}

uniticket/uni_ticket_bootstrap_italia_template/templates/ticket_detail_print.html
{% extends "base_page_schema.html" %}

{% load i18n %}
{% load static %}
{% load uni_ticket_tags %}

{% block extra_head %}
{{ block.super }}
<style>
.it-header-wrapper .it-nav-wrapper .it-brand-wrapper {
    padding-left: 0;
}
</style>
{% endblock extra_head %}

{% block header_slim_wrapper %}{% endblock %}
{% block header_center_right_zone %}{% endblock %}

{% block main_div_class %}{% endblock %}

{% block main_menu %}
<div class="container"><hr /></div>
{% endblock main_menu %}

{% block page_content %}
    {% block user_ticket_head %}
        {% if category_conditions %}
        <div class="pb-4">
            <div class="row">
                <div class="col">
                    <div class="card-space card-wrapper">
                        <div class="card card-bg no-after">
                            <div class="card-body">
                                {% include "ticket_detail_category_conditions.html" %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    {% endblock user_ticket_head %}

    {% block ticket_data %}
        {% include 'ticket_detail.html' with print_version=1 %}
        {% include 'ticket_task.html' with print_version=1 %}
    {% endblock ticket_data %}

    {{ ticket.input_module.ticket_category.footer_text | markdown | safe  }}

{% endblock page_content %}

{% block footer %}{% endblock %}
{% block form_buttons %}{% endblock %}
{% block bottom_scripts %}{% endblock %}

uniticket/uni_ticket_bootstrap_italia_template/templates/user_data.html
{% load i18n %}
{% load static %}

{% load accounts_tags %}
{% load uni_ticket_tags %}

<div class="row">
    <div class="col">
        <div class="card-wrapper card-space pb-3">
            <div class="card card-bg no-after">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <tbody>
                                <tr>
                                    <th scope="row">{% trans "Nome" %}</th>
                                    <td>{{ request.user.first_name|default:'-' }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">{% trans "Cognome" %}</th>
                                    <td>{{ request.user.last_name|default:'-' }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">{% trans "E-mail" %}</th>
                                    <td>{{ request.user.email|default:'-' }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">{% trans "Codice fiscale" %}</th>
                                    <td>{{ request.user.taxpayer_id|default:'-' }}</td>
                                </tr>
                                {% uni_ticket_settings_value "EMPLOYEE_ATTRIBUTE_NAME" as employee_attribute_name %}
                                {% uni_ticket_settings_value "EMPLOYEE_ATTRIBUTE_LABEL" as employee_attribute_label %}
                                {% obj_get_attr request.user employee_attribute_name as user_employee_attribute %}
                                {% if user_employee_attribute %}
                                    <tr>
                                        <th scope="row">{{ employee_attribute_label }}</th>
                                        <td>{{ user_employee_attribute }}</td>
                                    </tr>
                                {% endif %}
                                {% uni_ticket_settings_value "USER_ATTRIBUTE_NAME" as user_attribute_name %}
                                {% uni_ticket_settings_value "USER_ATTRIBUTE_LABEL" as user_attribute_label %}
                                {% obj_get_attr request.user user_attribute_name as user_user_attribute %}
                                {% if user_user_attribute %}
                                    <tr>
                                        <th scope="row">{{ user_attribute_label }}</th>
                                        <td>{{ user_user_attribute }}</td>
                                    </tr>
                                {% endif %}
                                <tr>
                                    <th scope="row">{% trans "Password" %}</th>
                                    <td><a href="{% url 'accounts:password_reset' %}">{% trans 'Modifica' %}</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    {% accounts_settings_value "EDITABLE_FIELDS" as accounts_editable_fields %}
                    {% if accounts_editable_fields %}
                    <div class="d-grid gap-2">
                        <a href="{% url 'accounts:change_data' %}" type="button" class="btn btn-success">
                            <svg class="icon icon-xs icon-white">
                                <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
                            </svg>
                            {% trans "Modifica" %}
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
   </div>
</div>