uniticket/accounts/urls.py
from django.urls import path

from . settings import EDITABLE_FIELDS
from . views import changeData, confirmEmail


app_name = "accounts"

if EDITABLE_FIELDS:
    urlpatterns = [
        # url(r'^login/$', Login, name='login'),
        # path('logout', Logout, name='logout'),
        path('account/edit/', changeData, name='change_data'),
        path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),
    ]
else: # pragma: no cover
    urlpatterns = []

uniticket/api_rest/urls.py
from django.urls import path, re_path
from django.utils.text import slugify

from rest_framework import routers
from rest_framework.renderers import JSONOpenAPIRenderer
from rest_framework.schemas import get_schema_view

from api_rest.views import generic, manager, operator, user

from uni_ticket.settings import MANAGEMENT_URL_PREFIX


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', generic.UserViewSet)
router.register('groups', generic.GroupViewSet)

app_name = "api_rest"

urlpatterns = [
    # path('api/', include(router.urls)),
    # path('api-auth/', include(rest_framework.urls, 'rest_framework',)),

    re_path('^openapi/$',  get_schema_view(**{}), name='openapi-schema'),
    re_path('^openapi.json/$', get_schema_view(renderer_classes = [JSONOpenAPIRenderer], **{}), name='openapi-schema-json'),

    # generic
    path('api/strutture/list/', generic.TicketAPIStruttureList.as_view(), name='api-strutture-list'),
    path('api/ticket/category/list/', generic.TicketAPITicketCategoryList.as_view(),name='api-ticket-category-list'),

    # user
    path('api/<slug:structure_slug>/<slug:category_slug>/ticket/new/', user.TicketAPIView.as_view(), name='api-new-ticket'),
    path('api/ticket/<str:ticket_uid>/', user.TicketAPIDetail.as_view(), name='api-view-ticket'),
    path('api/ticket/user/list/', user.TicketAPIListCreated.as_view(), name='api-ticket-user-list'),
    path('api/ticket/close/<str:ticket_id>/', user.TicketAPIClose.as_view(), name='api-ticket-close'),

    # manager
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/unassigned/count/', manager.TicketAPIUnassignedCounter.as_view(), name='api-manager-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/open/count/', manager.TicketAPIOpenCounter.as_view(), name='api-manager-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/my-open/count/', manager.TicketAPIMyOpenCounter.as_view(), name='api-manager-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["manager"])}/<slug:structure_slug>/tickets/messages/count/', manager.TicketAPIMessagesCounter.as_view(), name='api-manager-tickets-messages-count'),

    # operator
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/unassigned/count/', operator.TicketAPIUnassignedCounter.as_view(), name='api-operator-tickets-unassigned-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/open/count/', operator.TicketAPIOpenCounter.as_view(), name='api-operator-tickets-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/my-open/count/', operator.TicketAPIMyOpenCounter.as_view(), name='api-operator-tickets-my-open-count'),
    path(f'api/{slugify(MANAGEMENT_URL_PREFIX["operator"])}/<slug:structure_slug>/tickets/messages/count/', operator.TicketAPIMessagesCounter.as_view(), name='api-operator-tickets-messages-count'),
]

uniticket/app_io/urls.py
from django.urls import path

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from . views import *


app_name = "app_io"


base = f"{MANAGEMENT_URL_PREFIX['manager']}/<str:structure_slug>/categories/<str:category_slug>/app-io/services"


urlpatterns = [
    path(f'{base}/new/', new, name='app_io_services_new'),
    path(f'{base}/<int:service_id>/edit/', edit, name='app_io_services_edit'),
    path(f'{base}/<int:service_id>/enable/', enable, name='app_io_services_enable'),
    path(f'{base}/<int:service_id>/disable/', disable, name='app_io_services_disable'),
    path(f'{base}/<int:service_id>/delete/', delete, name='app_io_services_delete'),
]

uniticket/chat/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . api import ChatMessageModelViewSet, UserModelViewSet
from . import views

router = DefaultRouter()
router.register(r'message', ChatMessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')

app_name = "chat"

urlpatterns = [
    path(r'api/chat/', include(router.urls)),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('chat/random-vc-provider', views.random_vc_provider, name='random_vc_provider'),
]

uniticket/uni_ticket/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import path, re_path
from django.utils.text import slugify
from django.views.generic import RedirectView

from uni_ticket.settings import MANAGEMENT_URL_PREFIX

from .decorators import is_manager, is_operator, is_super_admin, is_the_owner
from .views import datatables, generic, management, manager, operator, user


app_name = "uni_ticket"

_dashboard_name = "dashboard"

# System/Generic URLs
# ticket = 'ticket/<str:ticket_id>'
ticket = "tickets/<str:ticket_id>"
urlpatterns = [
    path("", RedirectView.as_view(url="/{}/".format(_dashboard_name))),
    # Router url di responsabilità su struttura (manager/operator/user)
    re_path(
        r"^manage/(?:(?P<structure_slug>[-\w]+)(/)?)?$", generic.manage, name="manage"),
    # Attachments download
    path(
        "{}/download/attachment/<str:attachment>/".format(ticket),
        generic.download_attachment,
        name="download_attachment",
    ),
    path(
        "{}/messages/<str:reply_id>/download/attachment/".format(ticket),
        generic.download_message_attachment,
        name="download_message_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/attachment/".format(ticket),
        generic.download_task_attachment,
        name="download_task_attachment",
    ),
    path(
        "{}/tasks/<str:task_id>/download/closing-attachment/".format(ticket),
        generic.download_task_closing_attachment,
        name="download_task_closing_attachment",
    ),
    path(
        "<str:structure_slug>/<str:category_slug>/conditions/<int:condition_id>/download/attachment",
        generic.download_condition_attachment,
        name="download_condition_attachment",
    ),
    # Delete ticket message
    path(
        "messages/delete/<str:ticket_message_id>/",
        generic.ticket_message_delete,
        name="message_delete",
    ),
    path(
        "email-notify/update/", generic.email_notify_change, name="email_notify_change"
    ),
    path(
        "print/ticket/<str:ticket_id>/",
        user.ticket_detail_print,
        name="ticket_detail_print",
    ),
    path(
        "print/ticket/<str:ticket_id>/pdf/",
        user.download_ticket_pdf,
        name="ticket_detail_print_pdf",
    ),
]

# Datatables URLs
structure = "<str:structure_slug>"
urlpatterns += [
    # User json
    path(
        "user_all_tickets.json",
        datatables.user_all_tickets,
        name="user_all_tickets_json",
    ),
    path(
        "user_opened_ticket.json",
        datatables.user_opened_ticket,
        name="user_opened_ticket_json",
    ),
    path(
        "user_closed_ticket.json",
        datatables.user_closed_ticket,
        name="user_closed_ticket_json",
    ),
    path(
        "user_unassigned_ticket.json",
        datatables.user_unassigned_ticket,
        name="user_unassigned_ticket_json",
    ),
    # Manager json
    path(
        "{}/manager_unassigned_ticket.json".format(structure),
        datatables.manager_unassigned_ticket,
        name="manager_unassigned_ticket_json",
    ),
    path(
        "{}/manager_opened_ticket.json".format(structure),
        datatables.manager_opened_ticket,
        name="manager_opened_ticket_json",
    ),
    path(
        "{}/my/manager_opened_ticket.json".format(structure),
        datatables.manager_my_opened_ticket,
        name="manager_my_opened_ticket_json",
    ),
    path(
        "{}/manager_closed_ticket.json".format(structure),
        datatables.manager_closed_ticket,
        name="manager_closed_ticket_json",
    ),
    path(
        "{}/manager_all_tickets.json".format(structure),
        datatables.manager_all_tickets,
        name="manager_all_tickets_json",
    ),
    # Operator json
    path(
        "{}/operator_unassigned_ticket.json".format(structure),
        datatables.operator_unassigned_ticket,
        name="operator_unassigned_ticket_json",
    ),
    path(
        "{}/operator_opened_ticket.json".format(structure),
        datatables.operator_opened_ticket,
        name="operator_opened_ticket_json",
    ),
    path(
        f"{structure}/my/operator_opened_ticket.json",
        datatables.operator_my_opened_ticket,
        name="operator_my_opened_ticket_json",
    ),
    path(
        f"{structure}/operator_closed_ticket.json",
        datatables.operator_closed_ticket,
        name="operator_closed_ticket_json",
    ),
    path(
        f"{structure}/operator_all_tickets.json",
        datatables.operator_all_tickets,
        name="operator_all_tickets_json",
    ),
]

# Management URLs (manager and operator)
base = "manage/<str:structure_slug>"
tickets = "{}/tickets".format(base)
# ticket = '{}'.format(tickets)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)

urlpatterns += [
    # Export CSV
    # path('{}/export-csv/'.format(tickets), management.export_category_csv, name='export_category_csv'),
    # Export csv/zip
    path(
        "{}/export_detailed_report/".format(tickets),
        management.export_detailed_report,
        name="manage_export_detailed_report",
    ),
    # Tickets
    path(
        "{}/opened/".format(tickets),
        management.manage_opened_ticket_url,
        name="manage_opened_ticket_url",
    ),
    path(
        "{}/unassigned/".format(tickets),
        management.manage_unassigned_ticket_url,
        name="manage_unassigned_ticket_url",
    ),
    path(
        "{}/closed/".format(tickets),
        management.manage_closed_ticket_url,
        name="manage_closed_ticket_url",
    ),
    path(
        "{}/".format(tickets),
        management.manage_not_closed_ticket_url,
        name="manage_not_closed_ticket_url",
    ),
    path("{}/".format(tickets), management.manage_ticket_url,
         name="manage_ticket_url"),
    path(
        "{}/".format(ticket_id),
        management.manage_ticket_url_detail,
        name="manage_ticket_url_detail",
    ),
    path(
        "{}/messages/".format(ticket_id),
        management.ticket_message_url,
        name="manage_ticket_message_url",
    ),
    path(
        "{}/notes/".format(ticket_id),
        management.ticket_notes_url,
        name="manage_ticket_notes_url",
    ),
    path(
        "{}/notes/<int:note_id>/".format(ticket_id),
        management.ticket_note_url,
        name="manage_ticket_note_url",
    ),
    path(
        "{}/notes/<str:note_id>/delete/".format(ticket_id),
        management.ticket_note_delete,
        name="manage_ticket_note_delete",
    ),
    path(
        "{}/competence/add/".format(ticket_id),
        management.ticket_competence_add_url,
        name="add_ticket_competence_url",
    ),
    path(
        "{}/competence/leave/".format(ticket_id),
        management.ticket_competence_leave,
        name="leave_ticket_competence",
    ),
    path(
        "{}/dependence/add/".format(ticket_id),
        management.ticket_dependence_add_url,
        name="add_ticket_dependence_url",
    ),
    path(
        "{}/dependence/remove/<str:main_ticket_id>/".format(ticket_id),
        management.ticket_dependence_remove,
        name="remove_ticket_dependence",
    ),
    path(
        "{}/close/".format(ticket_id), management.ticket_close_url, name="close_ticket"
    ),
    path(
        "{}/reopen/".format(ticket_id), management.ticket_reopen, name="reopen_ticket"
    ),
    path(
        "{}/assign-offices/".format(ticket_id),
        management.ticket_taken_by_unassigned_offices,
        name="ticket_taken_by_unassigned_offices",
    ),
    # path('{}/assign/<str:destination_structure_slug>/<str:office_slug>/'.format(ticket_id), management.ticket_taken_by_unassigned_office, name='ticket_taken_by_unassigned_office'),
    # Task
    path(
        "{}/add/".format(task), management.task_add_new_url, name="add_ticket_task_url"
    ),
    path(
        "{}/".format(task_id), management.task_detail_url, name="manage_task_detail_url"
    ),
    path("{}/close/".format(task_id),
         management.task_close_url, name="close_task"),
    path("{}/delete/".format(task_id),
         management.task_remove, name="task_remove"),
    path("{}/riapri/".format(task_id),
         management.task_reopen, name="reopen_task"),
    path(
        "{}/edit/remove-attachment/".format(task_id),
        management.task_attachment_delete,
        name="manage_elimina_allegato_task",
    ),
    path("{}/edit/".format(task_id), management.task_edit_url, name="edit_task"),
]

# Manager URLs
base = "{}/<str:structure_slug>".format(
    slugify(MANAGEMENT_URL_PREFIX["manager"]))
tickets = "{}/tickets".format(base)
ticket_id = "{}/<str:ticket_id>".format(tickets)
task = "{}/tasks".format(ticket_id)
task_id = "{}/<str:task_id>".format(task)
offices = "{}/offices".format(base)
office = "{}/office".format(offices)
office_id = "{}/<str:office_slug>".format(office)
categories = "{}/categories".format(base)
# category = '{}/category'.format(categories)
category_id = "{}/<str:category_slug>".format(categories)
cat_input = "{}/input".format(category_id)
cat_input_id = "{}/<int:module_id>".format(cat_input)
condition = "{}/conditions".format(category_id)
condition_id = "{}/<int:condition_id>".format(condition)
default_reply = "{}/default_replies".format(category_id)
default_reply_id = "{}/<int:default_reply_id>".format(default_reply)
category_task = "{}/default-tasks".format(category_id)
category_task_id = "{}/<str:task_id>".format(category_task)

structure_protocol_configurations = "{}/settings/protocol-configurations".format(
    base)
structure_protocol_configuration = "{}/<int:configuration_id>".format(
    structure_protocol_configurations
)

category_protocol_configurations = "{}/protocol-configurations".format(
    category_id)
category_protocol_configuration = "{}/<int:configuration_id>".format(
    category_protocol_configurations
)

urlpatterns += [
    path(

uniticket/uni_ticket_bootstrap_italia_template/templates/management/statistics.html
{% extends 'user/dashboard.html' %}

{% load i18n %}
{% load static %}


{% block container_inner %}
{% include 'management/statistics_content.html' %}
{% endblock container_inner %}

uniticket/uni_ticket_bootstrap_italia_template/templates/management/statistics_manager.html
{% extends 'manager/dashboard.html' %}

{% load i18n %}
{% load static %}


{% block container_inner %}
{% include 'management/statistics_content.html' %}
{% endblock container_inner %}

uniticket/uni_ticket_bootstrap_italia_template/templates/management/statistics_superuser.html
{% extends 'user/dashboard.html' %}

{% load i18n %}
{% load static %}


{% block container_inner %}
{% include 'management/statistics_content.html' %}
{% endblock container_inner %}

uniticket/uni_ticket_bootstrap_italia_template/templates/management/task_edit.html
{% extends "form_complete.html" %}

{% load i18n %}
{% load static %}

{% block top_buttons %}
<a role="button" class="btn btn-outline-secondary"
   href="{% url 'uni_ticket:manage_task_detail_url' structure_slug=structure.slug ticket_id=task.ticket.code task_id=task.code %}">
    <svg class="icon icon-xs">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
    </svg> {% trans "Torna all'attività" %}
</a>
{% endblock top_buttons %}

{% block form_buttons %}
<div class="d-grid gap-2">
    <button class="btn btn-success" type="submit">
        <svg class="icon icon-xs icon-white">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-check"></use>
        </svg> {% trans 'Modifica attività' %}
    </button>
</div>
{% endblock form_buttons %}

{% block allegati %}
    <!--
    Se ci sono allegati inseriti
    -->
    {% if allegati %}
    <div class="pt-4">
        <h5>Allegati:</h5>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>{% trans "Nome campo" %}</th>
                        <th>{% trans "Nome file" %}</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for k,v in allegati.items %}
                        <tr>
                            <td class="collapsing">
                                <b>{{k}}</b>
                            </td>
                            <td>{{v}}</td>
                            <!--
                            Se la domanda è modificabile,
                            il pulsante Rimuovi allegato viene mostrato
                            -->
                            <td class="collapsing">
                                <button type="button"
                                        class="mx-1 btn btn-outline-danger btn-xs float-end"
                                        data-bs-toggle="modal"
                                        data-bs-target="#delete_allegato_{{ k }}">
                                    {% trans 'Elimina allegato' %}
                                </button>
                                <a download
                                   href="{% url 'uni_ticket:download_task_attachment' ticket_id=task.ticket.code task_id=task.code %}"
                                   role="button"
                                   class="mx-1 btn btn-outline-secondary btn-xs float-end">
                                    <i class="icon download"></i>
                                    Vedi allegato
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% for k,v in allegati.items %}
        <div class="modal fade" tabindex="-1" role="dialog" id="delete_allegato_{{ k }}">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            {% trans "Eliminazione allegato" %}
                        </h5>
                        <button class="btn-close"
                                type="button"
                                data-bs-dismiss="modal"
                                aria-label="Close">
                           <svg class="icon">
                              <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                           </svg>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>{% trans "Vuoi davvero eliminare l'allegato" %}
                            <b>{{ v }}</b> ?
                        </p>
                    </div>
                    <div class="modal-footer">
                        <a role="button"
                           class="btn btn-danger"
                           href="{% url 'uni_ticket:manage_elimina_allegato_task' structure_slug=structure.slug ticket_id=task.ticket.code task_id=task.code %}">
                           {% trans "Si, elimina" %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock allegati %}

uniticket/uni_ticket_bootstrap_italia_template/templates/management/ticket_options.html
{% extends "ticket_options.html" %}

{% load i18n %}
{% load static %}


{% block ticket_task %}
<div class="it-list-wrapper">
    <ul class="it-list">
        {% for task in ticket_task %}
        <li class="py-2 clearfix">
            <b>{{ task }}</b>
            <br>
            <small>{{ task.created }}</small>
            <br>
            {{ task.get_status|safe }}
            <div>
                {% if not ticket.is_closed %}
                <button type="button"
                    class="mx-1 btn btn-outline-danger btn-xs float-end"
                    data-bs-toggle="modal"
                    data-bs-target="#deleteTask{{ forloop.counter0 }}">
                    {% trans "Elimina attività" %}
                </button>
                {% else %}
                <button type="button"
                    class="mx-1 btn btn-secondary btn-xs float-end"
                    title="{% trans 'Questa attività non può essere eliminata' %}"
                    disabled>
                    {% trans "Elimina attività" %}
                </button>
                {% endif %}

                {% if task.is_closed %}
                <button type="button"
                    class="mx-1 btn btn-outline-warning btn-xs float-end"
                    data-bs-toggle="modal"
                    data-bs-target="#reopenTask{{ forloop.counter0 }}">
                    {% trans "Riapri attività" %}
                </button>
                {% else %}
                <a role="button"
                   class="mx-1 btn btn-outline-success btn-xs float-end"
                   href="{% url 'uni_ticket:close_task' structure_slug=structure.slug ticket_id=task.ticket.code task_id=task.code %}">
                    {% trans "Chiudi attività" %}
                </a>
                {% endif %}

                <a role="button"
                   class="mx-1 btn btn-outline-secondary btn-xs float-end"
                   href="{% url 'uni_ticket:manage_task_detail_url' structure_slug=structure.slug ticket_id=ticket.code task_id=task.code %}">
                    {% trans "Dettagli" %}
                </a>
            </div>

            {% if not ticket.is_closed %}
            <div class="modal fade"
                 tabindex="-1"
                 role="dialog"
                 id="deleteTask{{ forloop.counter0 }}">
                <div class="modal-dialog modal-dialog-centered"
                     role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">
                                {% trans "Eliminazione attività" %}
                            </h5>
                            <button class="btn-close" type="button"
                                    data-bs-dismiss="modal"
                                    aria-label="Close">
                               <svg class="icon">
                                  <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                               </svg>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>{% trans "Vuoi davvero eliminare l'attività dalla richiesta" %}
                               <br>
                               <b>{{ task }}</b> ?
                            </p>
                        </div>
                        <div class="modal-footer">
                            <a role="button" class="btn btn-danger"
                               href="{% url 'uni_ticket:task_remove' structure_slug=structure.slug ticket_id=ticket.code task_id=task.code %}">
                                {% trans "Si, elimina l'attività" %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            {% if task.is_closed %}
            <div class="modal fade" tabindex="-1" role="dialog" id="reopenTask{{ forloop.counter0 }}">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">
                                {% trans "Riapertura task" %}
                            </h5>
                            <button class="btn-close" type="button"
                                    data-bs-dismiss="modal" aria-label="Close">
                               <svg class="icon">
                                  <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                               </svg>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>{% trans "Vuoi davvero riaprire il task" %}
                               <br>
                               <b>{{ task }}</b> ?
                            </p>
                        </div>
                        <div class="modal-footer">
                            <a role="button" class="btn btn-warning"
                               href="{% url 'uni_ticket:reopen_task' structure_slug=structure.slug ticket_id=task.ticket.code task_id=task.code %}">
                                {% trans "Si, riapri il task" %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

        </li>
        {% endfor %}
    </ul>
</div>
<div class="d-grid gap-2">
    <a class="btn btn-outline-success mt-4"
       href="{% url 'uni_ticket:add_ticket_task_url' structure_slug=structure.slug ticket_id=ticket.code %}">
        <svg class="icon icon-xs icon-success">
            <use xlink:href="/static/svg/sprites.svg#it-plus-circle"></use>
        </svg> {% trans "Aggiungi nuova attività" %}
    </a>
</div>
{% endblock ticket_task %}

{% block ticket_dependences %}
<div class="it-list-wrapper">
    <ul class="it-list">
        {% for dependence in dependences %}
        <li class="py-2 clearfix">
            <b>{{ dependence.main_ticket }}</b>
            {% if dependence.main_ticket.is_closed %}
                <span class="badge bg-danger">
                    {% trans "Chiuso" %}
                </span>
            {% else %}
                <span class="badge bg-success">
                    {% trans "Aperto" %}
                </span>
            {% endif %}
            <br>
            {{ dependence.main_ticket.input_module.ticket_category }}
            [{{ dependence.main_ticket.input_module.ticket_category.organizational_structure }}]
            {% if dependence.note %}
            <br>
            <i>{{ dependence.note }}</i>
            {% endif %}

            {% if not ticket.is_closed %}
            <button type="button"
                class="mx-1 btn btn-outline-danger btn-xs float-end"
                data-bs-toggle="modal"
                data-bs-target="#deleteDependence{{ forloop.counter0 }}">
                {% trans "Rimuovi dipendenza" %}
            </button>
            <div class="modal fade"
                 tabindex="-1"
                 role="dialog"
                 id="deleteDependence{{ forloop.counter0 }}">
                <div class="modal-dialog modal-dialog-centered"
                     role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">
                                {% trans "Eliminazione dipendenza" %}
                            </h5>
                            <button class="btn-close" type="button"
                                    data-bs-dismiss="modal"
                                    aria-label="Close">
                               <svg class="icon">
                                  <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                               </svg>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>{% trans "Vuoi davvero eliminare la dipendenza dalla richiesta" %}
                               <br>
                               <b>{{ dependence }}</b> ?
                            </p>
                        </div>
                        <div class="modal-footer">
                            <a role="button" class="btn btn-danger"
                               href="{% url 'uni_ticket:remove_ticket_dependence' structure_slug=structure.slug ticket_id=ticket.code main_ticket_id=dependence.main_ticket.code %}">
                                {% trans "Si, elimina la dipendenza" %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <a role="button"
               class="mx-1 btn btn-outline-secondary btn-xs float-end"
               href="{% url 'uni_ticket:manage_ticket_url_detail' structure_slug=structure.slug ticket_id=dependence.main_ticket.code %}">
                {% trans "Vai alla richiesta" %}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="d-grid gap-2">
    <a class="btn btn-outline-success mt-4"
       href="{% url 'uni_ticket:add_ticket_dependence_url' structure_slug=structure.slug ticket_id=ticket.code %}">
        <svg class="icon icon-xs icon-success">
            <use xlink:href="/static/svg/sprites.svg#it-plus-circle"></use>
        </svg> {% trans "Aggiungi nuova dipendenza" %}
    </a>
</div>
{% endblock ticket_dependences %}